// server/cards.js

// --- SİYAH KARTLAR (SORULAR) ---
const blackCards = [
    // === BÖLÜM 1: TEK CEVAPLI (PICK 1) ===
    // -- Klasikler & Genel --
    { text: "Tarihteki en kötü icat nedir?", pick: 1 },
    { text: "Sevgilimin beni terk etme sebebi: ___.", pick: 1 },
    { text: "Doktor bey, röntgenimde ___ görünüyor, bu normal mi?", pick: 1 },
    { text: "Annem ___ yaparken beni yakaladı.", pick: 1 },
    { text: "Cennette ___ tonla bulunur.", pick: 1 },
    { text: "Bu gece rüyamda ___ gördüm.", pick: 1 },
    { text: "Zengin olunca ilk işim ___ satın almak.", pick: 1 },
    { text: "Dedemin son sözleri: ___.", pick: 1 },
    { text: "Savaş neye yarar? ___.", pick: 1 },
    { text: "Hayatı ne yaşamaya değer kılar?", pick: 1 },
    { text: "Bana ne kontrol edilemez bir gaz verir?", pick: 1 },
    { text: "Bu koku da ne?", pick: 1 },
    { text: "Geceleri neden uyuyamıyorum?", pick: 1 },

    // -- Türkiye Gündemi & Siyaset --
    { text: "Erdoğan'ın yeni projesi: ___.", pick: 1 },
    { text: "Türkiye'nin en büyük sorunu ___ değil, ___.", pick: 1 },
    { text: "Metrobüste yanıma ___ oturdu.", pick: 1 },
    { text: "Son dakika! Merkez Bankası faiz kararını açıkladı: Artık ___ geçerli.", pick: 1 },
    { text: "Taksicilerin kısa mesafe almama sebebi aslında ___.", pick: 1 },
    { text: "Fatih Terim Fonu'ndan bana sadece ___ kaldı.", pick: 1 },
    { text: "KYK yurdu asansöründe ___ ile karşılaştım.", pick: 1 },
    { text: "Deprem çantamda olması gereken en önemli şey: ___.", pick: 1 },
    { text: "Suriyeli din kardeşlerimiz şimdi de ___ istiyor.", pick: 1 },
    { text: "Seçim gecesi verilerin kaybolma sebebi: ___.", pick: 1 },
    { text: "Diyanet İşleri'nin yeni fetvası: ___ haramdır.", pick: 1 },
    { text: "Sedat Peker'in bir sonraki videosunun konusu: ___.", pick: 1 },
    { text: "Togg'un bagajından ___ çıktı.", pick: 1 },
    { text: "Ülkeyi kurtaracak tek şey ___.", pick: 1 },

    // -- Pop Kültür & Medya --
    { text: "Bülent Ersoy'un makyaj çantasından ___ çıktı.", pick: 1 },
    { text: "Survivor'da diskalifiye olma sebebim: ___.", pick: 1 },
    { text: "Youtube trendlerinde 1. sırada ne var?", pick: 1 },
    { text: "Müge Anlı'da bugün: 'Yardım! Oğlum ___!'", pick: 1 },
    { text: "Netflix'in yeni Türk dizisinde başrol ___ ile sevişiyor.", pick: 1 },
    { text: "Exxen'in çökme sebebi: ___.", pick: 1 },
    { text: "Şeyma Subaşı'nın nafaka parasıyla aldığı ilk şey: ___.", pick: 1 },
    { text: "Acun Ilıcalı'nın satın alamadığı tek şey: ___.", pick: 1 },
    { text: "Aleyna Tilki'nin parmağı ___ kokuyor.", pick: 1 },
    { text: "Adnan Oktar'ın kediciklerine verdiği gizli görev: ___.", pick: 1 },

    // -- Absürt & Dark Mizah --
    { text: "Dilan Polat'ın enerjiiiiiisi aslında ___ kaynağından geliyormuş.", pick: 1 },
    { text: "OnlyFans açan teyzenin ilk paylaşımı: ___.", pick: 1 },
    { text: "İmam hatip lisesi tuvaletinde ___ bulundu.", pick: 1 },
    { text: "Mahalle yanarken orospu ___ yaparmış.", pick: 1 },
    { text: "Babama 'Gayim' dediğimde bana ___ verdi.", pick: 1 },
    { text: "Sünnet düğünümde kirvem ___ idi.", pick: 1 },
    { text: "Kız arkadaşımın 'Reglim' demesi aslında ___ demek.", pick: 1 },
    { text: "___ yüzünden cehenneme gideceğim.", pick: 1 },
    { text: "Çocuk güzellik yarışmaları ___ için bir kılıftır.", pick: 1 },

    // === BÖLÜM 2: ÇİFT CEVAPLI (PICK 2) - DAHA ZORLU ===
    { text: "___ ile ___ harika bir ikili olurdu.", pick: 2 },
    { text: "Adım Bond. ___ Bond. ___ severim.", pick: 2 },
    { text: "Evet arkadaşlar kanalıma hoşgeldiniz, bugün ___ ile ___ yapacağız.", pick: 2 },
    { text: "___, ___ için en iyi ilaçtır.", pick: 2 },
    { text: "Hayat, ___ ile başlar, ___ ile biter.", pick: 2 },
    { text: "Bir elime ___, diğer elime ___ aldım.", pick: 2 },
    { text: "Yüzyılın kapışması: ___ vs ___.", pick: 2 },
    { text: "___ yüzünden ___ yapmak zorunda kaldım.", pick: 2 },
    { text: "Annem hep derdi ki: Oğlum/Kızım ___ yapma, yoksa ___ olursun.", pick: 2 },
    { text: "Türkiye'de ___ yasak ama ___ serbest.", pick: 2 },
    { text: "Müsaadenizle beyler, ___ ile randevum var. ___ getireceğim.", pick: 2 },
    { text: "Sevdiceğinle ___ olamıyorsan yerine ___ sev.", pick: 2 },
    { text: "Bize çılgınsınız dediler. Bize ___ içine ___ koyamazsınız dediler. Yanıldılar.", pick: 2 },
    { text: "İlk buluşmada ___ sipariş ettim, sonra da ___ teklif ettim.", pick: 2 }
];

// --- BEYAZ KARTLAR (CEVAPLAR) ---
const whiteCards = [
    // === BÖLÜM 1: SİYASET & TÜRKİYE GÜNDEMİ ===
    "Recep Tayyip Erdoğan",
    "Kılıçdaroğlu'nun faturası",
    "Devlet Bahçeli",
    "Meral Akşener",
    "Süleyman Soylu",
    "Abdullah OCalan",
    "Sedat Peker",
    "İstanbul Sözleşmesi",
    "Mansur Yavaş'ın sessizliği",
    "Ekrem İmamoğlu'nun tatili",
    "Vergi Dairesi",
    "Silivri soğuktur şimdi",
    "Dolar kuru",
    "Euro kuru",
    "Çeyrek altın",
    "Soğan fiyatları",
    "Enflasyon canavarı",
    "Faiz lobisi",
    "Dış güçlerin oyunu",
    "Lozan'ın gizli maddeleri",
    "Jelibon rezervi",
    "Pudra şekeri çeken AK Partili",
    "Diyanet'in Mercedes'i",
    "Suriyeli din kardeşlerimiz",
    "Afgan mülteciler",
    "Troll ordusu",
    "Beşli çete",
    "Yandaş medya",
    "A Haber izleyen dayı",
    "Seçim gecesi kaybolan veriler",
    "Togg'un bagajı",
    "6'lı masa",
    "Askıda ekmek",
    
    // === BÖLÜM 2: ÜNLÜLER, TV & İNTERNET ===
    "Acun Ilıcalı",
    "Şeyma Subaşı'nın kitabı",
    "Müge Anlı",
    "Esra Erol'da DNA testi",
    "Seda Sayan'ın çorapları",
    "Bülent Ersoy'un divası",
    "İbrahim Tatlıses'in çiğ köftesi",
    "Nihat Hatipoğlu ile İftar",
    "Cübbeli Ahmet Hoca",
    "Adnan Oktar'ın kedicikleri",
    "Polat Alemdar",
    "Memati Baş",
    "Süleyman Çakır",
    "Behzat Ç.",
    "Recep İvedik",
    "Cem Yılmaz",
    "Aleyna Tilki",
    "Kerimcan Durmaz",
    "Danla Bilic",
    "Enes Batur",
    "Jahrein'in kilosu",
    "Oğuzhan Uğur",
    "Fatih Terim Fonu",
    "Dilan Polat'ın enerjiiiiiisi",
    "Flash TV halayı",
    "Kısmetse Olur Cansel",
    "Masterchef Mehmet Şef",
    "Zeki Müren",
    "Ajda Pekkan'ın estetikleri",
    
    // === BÖLÜM 3: CİNSELLİK & VÜCUT (NSFW) ===
    "Otuz bir",
    "Seks",
    "Anal seks",
    "Grup seks",
    "Gay bar",
    "Genelev",
    "Göt ve Deliği",
    "Pezevenk",
    "Orospu",
    "Kerhane tatlısı",
    "Kondom",
    "Kürtaj",
    "Sünnet düğünü",
    "Onlyfans",
    "Ayak fetişi",
    "Mastürbasyon",
    "Pornografi",
    "Fetiş",
    "Vibrator",
    "Dildo",
    "Seks oyuncağı",
    "Sünnet derisi pilavı",
    "Annenin Amcığı",
    "Dedemin ereksiyonu",
    "Babaannemin takma dişleri",
    "Koltuk altı kılı",
    "Osuruk",
    "İshal",
    "Basur",
    "Ölü bir fahişe",
    "Bir kova dolusu sperm",
    "İkinci el dildo",
    "Patlak prezervatif",
    "Islak tuvalet terliği",
    "Regl kanı",
    "Sabah ereksiyonu",
    "Erken boşalma",
    "İktidarsızlık",
    "Viagra",
    "Travesti",
    "Pasif gay",
    "Aktif gay",
    "Lezbiyen",
    "Ensest ilişki",
    "Sadist",
    "Mazoşist",
    "Ayak fetişi",
    "BDSM",
    "Kelepçe",
    "Kırbaç",
    "Gangbang",
    "Anal Fisting",
    "Lateks eldiven",
    "Erotik masaj",
    "Striptiz kulübü",
    "Çıplak dans",
    "Oral seks",
    "69",
    "Doggy style",
    "Kucak dansı",
    "Mutlu sonlu masaj",
    "Tecavüz",
    "Nuri Alço'nun gazozu",
    "Şahin K",
    "Haydar Dümen",
    
    // === BÖLÜM 4: ABSÜRT, KARA MİZAH & İĞRENÇLİK ===
    "Anan",
    "Yavru köpekler!",
    "Ölü bebekler",
    "Nazi altını",
    "Adolf Hitler",
    "Yahudi sabunu",
    "11 Eylül",
    "Yetimhane yangını",
    "Kanalizasyon",
    "Babamın gizli porno arşivi",
    "Mülteci kampında swinger partisi",
    "Kürtaj artığı",
    "Engelli tuvaletinde sigara içmek",
    "Çocuklara uyuşturucu satmak",
    "Nekrofili",
    "Zoofili",
    "Yamyamlık",
    "İntihar bombacısı",
    "Canlı bomba yeleği",
    "Seri katil",
    "Pedofiller",
    "Ensest ilişki",
    "Tırnak Kiri",
    "Ayak teri",
    "Ağız kokusu",
    "Kendi kendine yanma",
    "Bir kavanoz dolusu tırnak",
    "Kusmuk",
    "Bok",
    "İnsan eti",
    "Sümüklü bebek",
    "Radyasyon",
    "Çernobil",
    
    // === BÖLÜM 5: GÜNLÜK HAYAT & EŞYALAR ===
    "Bim poşeti",
    "A101 Harca Harca Bitmez",
    "Şok market çalışanının yorgunluğu",
    "Metrobüs",
    "Marmaray",
    "Taksi şoförü",
    "Dolmuşçu dayı",
    "Tofaş Şahin",
    "Doblo enişte",
    "Mangal keyfi",
    "Rakı masası",
    "Çiğ köfte",
    "Lahmacun",
    "Kokoreç",
    "Midye dolma",
    "Simit ayran",
    "Tavuk döner",
    "Islak hamburger",
    "Türk kahvesi",
    "Oralet",
    "Aras Kargo",
    "Yurtiçi Kargo (Evde yoktunuz)",
    "Getir kuryesi",
    "Martı'ya binen 3 kişi",
    "KYK yurdu yemeği",
    "Öğrenci evi makarnası",
    "Biten diş macunu",
    "Dantelli televizyon örtüsü",
    "Altın günü",
    "Kısır",
    "Börek",
    "Düğün konvoyu",
    "Korna sesi",
    
    // === BÖLÜM 6: KAVRAMLAR & DURUMLAR ===
    "Fakirlik",
    "Zenginlik",
    "Yalnızlık",
    "Depresyon",
    "Anksiyete",
    "Panik atak",
    "Varoluşsal sancı",
    "Pazartesi sendromu",
    "Cuma namazı",
    "Bayram namazı",
    "Ramazan davulcusu",
    "Sahur",
    "İftar",
    "Oruç tutmayan dayak yiyen adam",
    "Cehennem",
    "Cennet",
    "Şeytan",
    "Allah",
    "Melek",
    "Mucize",
    "Kabe",
    "Kader",
    "Kuran",
    "Hadis",
    "İncil",
    "Tevrat",
    "Mabet",
    "Kısmet",
    "Nazar",
    "Büyü",
    "Muska",
    "Cin çarpması",
    "Üç harfliler",
    "Paralel evren",
    "Uzaylılar",
    "Büyük Patlama",
    "Kıyamet günü",
    "Zombi istilası"
];

module.exports = { blackCards, whiteCards };